---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
knitr::opts_chunk$set(echo = TRUE)
```

Loading CSV from directory
As per github directory, the .Rmd file and activity.csv should be in the same place
```{r}

activityFile <- read.csv("./activity.csv")


```


## What is mean total number of steps taken per day?


```{r}
dailySteps <- with(activityFile, aggregate(steps, by = list(date), FUN = sum, na.rm = TRUE))
names(dailySteps) <- c("date", "steps")

hist(dailySteps$steps, main = "Total Daily Steps", col="red", xlab = "Steps Taken per day" , breaks = seq(0,25000, by = 1000))

meanDailySteps <- mean(dailySteps$steps)

```

## What is the average daily activity pattern?

```{r}
dailyActivity <- aggregate(activityFile$steps, by = list(activityFile$interval), FUN = mean, na.rm = TRUE)
names(dailyActivity) <- c("interval", "meanSteps")
plot(dailyActivity$interval, dailyActivity$meanSteps, type = "l", col="red", lwd = 2, ylab="Mean Steps", xlab="Interval", main="Mean Steps Per Interval")

```

## Imputing missing values
```{r}
meanStepsImputed <- dailyActivity$meanSteps[match(activityFile$interval, dailyActivity$interval)]

activityFileNoNa <- transform(activityFile, steps = ifelse(is.na(activityFile$steps), yes = meanStepsImputed, no = activityFile$steps))

dailyStepsNoNa <- aggregate(steps ~ date, activityFileNoNa, sum)
names(dailyStepsNoNa) <- c("date", "steps")

hist(dailyStepsNoNa$steps, main = "Total Daily Steps", col="red", xlab = "Steps Taken per day" , breaks = seq(0,25000, by = 1000))

meanDailyStepsNoNa <- mean(dailyStepsNoNa$steps)


```
## Are there differences in activity patterns between weekdays and weekends?

```{r}

library(ggplot2)

activityFileDays <- activityFile

activityFileDays$date <- as.POSIXct(activityFileDays$date) 

dayColumn <- weekdays(activityFileDays$date)

activityFileDays <- cbind(activityFileDays, dayColumn)


isWeekend <- function(x) {
  dayType <- x
  
  if (x %in% c("Saturday", "Sunday"))
    return("Weekend")
  else
    return("Weekday")
}

activityFileDays$dayColumn <- sapply(activityFileDays$dayColumn, FUN=isWeekend)

activityFileDaysNoNa <- aggregate(activityFileDays$steps~activityFileDays$interval + activityFileDays$dayColumn, activityFileDays, mean, na.rm = TRUE)
names(activityFileDaysNoNa) <- c("interval", "dayColumn", "steps")


weekdayPlot <- ggplot(activityFileDaysNoNa, aes(x=interval, y=steps,colour=dayColumn )) + geom_line() + labs(title="Mean steps Weekday vs Weekend", x="Interval", y="Mean Steps per Interval") + facet_wrap(~dayColumn, ncol=1, nrow=2)

print(weekdayPlot)
```